### ISSUE TITLE
World of Warcraft is also getting protected soon!

### ISSUE THREAD

**Issue by reliasn** [changeofpace/Overwatch-Dump-Fix#2]
Blizzard is applying on WoW a protection quite similar to Overwatch: http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/632261-free-lunch-over-obfuscation-coming.html

I've been testing your snippets, especially the Force-Page-Protection plugin that you created, but I'm having a couple issues where NtMapViewOfSection returns 0xc0000220. Also, NtUnmapViewOfSection seems to unmap from the start of Wow's module instead of unmapping only the page that I chose.

**Comment by changeofpace** [comment]
Your mapped views must have a base address that is aligned to the system allocation granularity.  NtUnmapViewOfSection unmaps the entire view which contains the base address parameter.

I don't use skype or discord, but you can message me on [unknowncheats](https://www.unknowncheats.me/forum/members/975835.html).

**Comment by reliasn** [comment]
After messing around with it, I got it working fine, but I kept the issue opened because I still wanted to reach you :)

I tried to contact you on unknowncheats but I can't send you a PM due to low post count:
![](https://i.imgur.com/jkYE0Ax.png)
I'm more active on [Ownedcore](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/501283-ewt-easy-wow-toolbox-fishing-farming-hacks-morpher-lua-unlocker-more.html).

There's the visitor messages in UC but I'm not sure if it's ideal. Don't you use any other chat communication software?

**Comment by reliasn** [comment]
Even though you PM'd me on UC, I can't reply to you:
![](https://i.imgur.com/zGMXYv6.png)

I will see if I can reach that 4-post limit 😄

**Comment by okwinza** [comment]
ping @changeofpace 
Do you have any plans regarding wow obfuscation yet? Just curious.

**Comment by changeofpace** [comment]
I'll check it out at some point. Does the current release have the updated obfuscation?

**Comment by okwinza** [comment]
The obfuscation is live since 29 Aug. Not sure if they changed it in any way after that.
