### ISSUE TITLE
Dump wow but could not run.

### ISSUE THREAD

**Issue by vkyii** [changeofpace/Overwatch-Dump-Fix#6]
Hi, I try to dump wow(classic 1.13.2.31727), but Wow_dump_SCY.exe could't run.

I notice that there are 2 invalid imports:

![image](https://user-images.githubusercontent.com/373150/64405453-c1292a00-d0b1-11e9-9a02-852c8869b1eb.png)

![image](https://user-images.githubusercontent.com/373150/64405717-74921e80-d0b2-11e9-97ac-64e059494905.png)

Is that the cause of failure?

**Comment by changeofpace** [comment]
The Scylla log indicates that the dump and rebuild were successful. Are you able to disassemble the dump file using IDA?

Scylla considers these two imports to be invalid because they are located in Wow's image region. This should not affect the plugin.

**Comment by vkyii** [comment]
Yes, IDA can disassemble the dump file.

I thought that running _Wow_dump_SCY.exe_ instead of the original _wow.exe_ can bypass the anti-debugging. :(

**Comment by changeofpace** [comment]
The plugin removes obfuscation from the (re)mapped image so that Scylla can generate a dump file with reconstructed imports. The dump file is meant to be statically analyzed with IDA or another disassembler.

**Comment by changeofpace** [comment]
The plugin removes obfuscation from the (re)mapped image so that Scylla can generate a dump file with reconstructed imports. The dump file is meant to be statically analyzed with IDA or another disassembler.

**Comment by megacoderencoderdecoder** [comment]
> The plugin removes obfuscation from the (re)mapped image so that Scylla can generate a dump file with reconstructed imports. The dump file is meant to be statically analyzed with IDA or another disassembler.

@changeofpace works same as in Warcraft III Reforged, but i got obfuscated functions plugin can't deobfuscate them ?? 
https://github.com/changeofpace/Overwatch-Dump-Fix/issues/9
